### ISSUE TITLE
WWW-Authenticate response header

### ISSUE THREAD

**Issue by fuadsaud** [kelveden/ring-jwt#3]
I see that this lib currently doesn't support a `WWW-Authenticate` header in the response. The OAuth 2.0 protocol (which frequently makes use of JWT as access tokens) [specifies a schema for the header in some error cases](https://www.rfc-editor.org/rfc/rfc6750#section-3), such as an expired or invalid token or if a required token is missing.

Is there any interest in supporting this? If so I might take a shot at proposing an API for it.

**Comment by kelveden** [comment]
Thanks for the idea. I'm not keen on it to be honest though as what you're talking about adding is something specific to OAuth rather than related to JWTs per se. So, I'd argue that this should be solved by a separate piece of OAuth-specific middleware that intercepts the response and adds on a `WWW-Authenticate` response header.

**Comment by fuadsaud** [comment]
The `WWW-Authenticate` header is not OAuth specific: [it is part of the HTTP standard](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) and, by the spec, [it is required in 401 responses. ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401).

I agree that the actual value of the header might be specific to the authentication scheme (in this case, specified by OAuth).

The problem is that, currently, this library generated its own 401 responses, for example, when the token is invalid.

A possible solution would be to include some extra information on the response map containing the reason for the 401. This could be processed by some wrapping OAuth middleware to enrich the response with the appropriate header value. Would that make sense?

**Comment by kelveden** [comment]
Sorry, your response slipped through the cracks and I've only just noticed it.

Yes, I do see your point now. I think that you're right, there should be a `WWW-Authenticate` response header in the `401` responses. I'll take a look when I get a moment.

**Comment by kelveden** [comment]
Added functionality in 2.10.0.
